#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800

#define UPDATE_RATE_MS 400

#define CELL_SIZE 20

#define GRID_X (SCREEN_WIDTH / CELL_SIZE)
#define GRID_Y (SCREEN_HEIGHT / CELL_SIZE)

